# Generated by Django 2.1.9 on 2019-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('custom_id', models.BigIntegerField()),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
            ],
        ),
    ]
