# Generated by Django 2.1.9 on 2019-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190625_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.BigIntegerField()),
                ('cohort_date', models.DateField()),
                ('cohort_index', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
