# Generated by Django 2.1.9 on 2019-06-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='custom_id',
            new_name='customer_id',
        ),
    ]
